services:
    PoP\CustomPostMedia\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true

    PoP\CustomPostMedia\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true
