services:
    PoP\PostMedia\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true

    PoP\PostMedia\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true
